-- UP
ALTER TABLE requests ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS submitter_name TEXT;

-- DOWN
ALTER TABLE requests DROP COLUMN IF EXISTS submitter_name;
ALTER TABLE requests DROP COLUMN IF EXISTS team;
ALTER TABLE requests ALTER COLUMN user_id SET NOT NULL;
